import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
          <div className="lg:flex hidden">
            <div className="w-1/5 h-screen fixed hidden md:block">
              <SideBar />
            </div>
            <div className="flex-1" style={{ paddingLeft: "20%" }}>
              {children}
            </div>
          </div>
          <div className="lg:hidden">
            <div className="flex-1 -z-20">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
